-- +goose Up
ALTER TABLE magic_link_tokens
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
  ALTER COLUMN expires_at TYPE TIMESTAMPTZ,
  ALTER COLUMN revoked_at TYPE TIMESTAMPTZ;

ALTER TABLE refresh_tokens
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
  ALTER COLUMN expires_at TYPE TIMESTAMPTZ,
  ALTER COLUMN revoked_at TYPE TIMESTAMPTZ;

ALTER TABLE users
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ;