// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (user_id, service, channel_id, channel_handle, access_token, refresh_token, token_expires_at, scopes)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id, created_at, updated_at, user_id, service, channel_id, channel_handle, access_token, refresh_token, token_expires_at, scopes, active
`

type CreateConnectionParams struct {
	UserID         uuid.UUID
	Service        Service
	ChannelID      string
	ChannelHandle  string
	AccessToken    string
	RefreshToken   sql.NullString
	TokenExpiresAt sql.NullTime
	Scopes         string
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, createConnection,
		arg.UserID,
		arg.Service,
		arg.ChannelID,
		arg.ChannelHandle,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.Scopes,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Service,
		&i.ChannelID,
		&i.ChannelHandle,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.Active,
	)
	return i, err
}

const getConnectionWithID = `-- name: GetConnectionWithID :one
SELECT id, created_at, updated_at, user_id, service, channel_id, channel_handle, access_token, refresh_token, token_expires_at, scopes, active
FROM connections
WHERE id = $1
`

func (q *Queries) GetConnectionWithID(ctx context.Context, id uuid.UUID) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnectionWithID, id)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Service,
		&i.ChannelID,
		&i.ChannelHandle,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.Active,
	)
	return i, err
}

const getConnections = `-- name: GetConnections :many
SELECT id, created_at, updated_at, user_id, service, channel_id, channel_handle, access_token, refresh_token, token_expires_at, scopes, active
FROM connections
WHERE user_id = $1
`

func (q *Queries) GetConnections(ctx context.Context, userID uuid.UUID) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, getConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connection
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Service,
			&i.ChannelID,
			&i.ChannelHandle,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleConnection = `-- name: ToggleConnection :one
UPDATE connections
SET updated_at = NOW(),
  active = $2
WHERE id = $1
RETURNING id, created_at, updated_at, user_id, service, channel_id, channel_handle, access_token, refresh_token, token_expires_at, scopes, active
`

type ToggleConnectionParams struct {
	ID     uuid.UUID
	Active bool
}

func (q *Queries) ToggleConnection(ctx context.Context, arg ToggleConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, toggleConnection, arg.ID, arg.Active)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Service,
		&i.ChannelID,
		&i.ChannelHandle,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.Active,
	)
	return i, err
}
