// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createConnection = `-- name: CreateConnection :one
INSERT INTO connections (user_id, service, channel_id, channel_handle, access_token, refresh_token, token_expires_at, scopes)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id, created_at, updated_at, user_id, service, channel_id, channel_handle, access_token, refresh_token, token_expires_at, scopes
`

type CreateConnectionParams struct {
	UserID         uuid.UUID
	Service        Service
	ChannelID      string
	ChannelHandle  string
	AccessToken    string
	RefreshToken   sql.NullString
	TokenExpiresAt sql.NullTime
	Scopes         string
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, createConnection,
		arg.UserID,
		arg.Service,
		arg.ChannelID,
		arg.ChannelHandle,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.Scopes,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Service,
		&i.ChannelID,
		&i.ChannelHandle,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
	)
	return i, err
}
