// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_link_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMagicLinkToken = `-- name: CreateMagicLinkToken :one
INSERT INTO magic_link_tokens (token, created_at, updated_at, user_id, expires_at)
VALUES (
  $1,
  NOW(),
  NOW(),
  $2,
  NOW() + INTERVAL '1 hour'
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateMagicLinkTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error) {
	row := q.db.QueryRowContext(ctx, createMagicLinkToken, arg.Token, arg.UserID)
	var i MagicLinkToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getMagicLinkTokenByToken = `-- name: GetMagicLinkTokenByToken :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at
FROM magic_link_tokens
WHERE token = $1
`

func (q *Queries) GetMagicLinkTokenByToken(ctx context.Context, token string) (MagicLinkToken, error) {
	row := q.db.QueryRowContext(ctx, getMagicLinkTokenByToken, token)
	var i MagicLinkToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeMagicLinkToken = `-- name: RevokeMagicLinkToken :exec
UPDATE magic_link_tokens
SET updated_at = NOW(),
  revoked_at = NOW()
WHERE token = $1
`

func (q *Queries) RevokeMagicLinkToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeMagicLinkToken, token)
	return err
}
