// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Connection struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	UserID         uuid.UUID
	Service        Service
	ChannelID      string
	ChannelHandle  string
	AccessToken    string
	RefreshToken   sql.NullString
	TokenExpiresAt sql.NullTime
	Scopes         string
	Active         bool
}

type MagicLinkToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	Name      sql.NullString
}

type OauthState struct {
	Token         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ExpiresAt     time.Time
	UserID        uuid.UUID
	Service       Service
	ChannelID     string
	ChannelHandle string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Report struct {
	ID            uuid.UUID
	Name          string
	TrackingStart time.Time
	TrackingEnd   sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword sql.NullString
	Language       Language
	Role           Role
	Name           sql.NullString
}

type UserReport struct {
	UserID    uuid.UUID
	ReportID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}
