// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_states.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthState = `-- name: CreateOAuthState :one
INSERT INTO oauth_states (token, expires_at, user_id, service, channel_id, channel_handle)
VALUES (
  $1,
  NOW() + INTERVAL '5 minutes',
  $2,
  $3,
  $4,
  $5
)
RETURNING token, created_at, updated_at, expires_at, user_id, service, channel_id, channel_handle
`

type CreateOAuthStateParams struct {
	Token         string
	UserID        uuid.UUID
	Service       Service
	ChannelID     string
	ChannelHandle string
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) (OauthState, error) {
	row := q.db.QueryRowContext(ctx, createOAuthState,
		arg.Token,
		arg.UserID,
		arg.Service,
		arg.ChannelID,
		arg.ChannelHandle,
	)
	var i OauthState
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.Service,
		&i.ChannelID,
		&i.ChannelHandle,
	)
	return i, err
}

const deleteOAuthStateFromToken = `-- name: DeleteOAuthStateFromToken :exec
DELETE FROM oauth_states
WHERE token = $1
`

func (q *Queries) DeleteOAuthStateFromToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthStateFromToken, token)
	return err
}

const getOAuthStateFromToken = `-- name: GetOAuthStateFromToken :one
SELECT token, created_at, updated_at, expires_at, user_id, service, channel_id, channel_handle
FROM oauth_states
WHERE token = $1
`

func (q *Queries) GetOAuthStateFromToken(ctx context.Context, token string) (OauthState, error) {
	row := q.db.QueryRowContext(ctx, getOAuthStateFromToken, token)
	var i OauthState
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.Service,
		&i.ChannelID,
		&i.ChannelHandle,
	)
	return i, err
}
