// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (name, tracking_start, tracking_end, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  NOW(),
  NOW()
)
RETURNING id, name, tracking_start, tracking_end, created_at, updated_at
`

type CreateReportParams struct {
	Name          string
	TrackingStart time.Time
	TrackingEnd   sql.NullTime
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport, arg.Name, arg.TrackingStart, arg.TrackingEnd)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TrackingStart,
		&i.TrackingEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
